@echo off
color a
goto 1

:1
cls
set /p input=Type in any number between 1-10:
if /i %input%==1, goto 2
if /i %input%==2, goto 3
if /i %input%==3, goto 4
if /i %input%==4, goto 5
if /i %input%==5, goto 6
if /i %input%==6, goto 7
if /i %input%==7, goto 8
if /i %input%==8, goto 9
if /i %input%==9, goto 10
if /i %input%==10, goto 11
if /i not %input%==1,2,3,4,5,6,7,8,9,10, goto error

:2
echo Analyzing brainwaves...
echo Scanning memories...
echo Calculating probabilities...
echo Decoding thoughts...
echo You are thinking of the number %input%.
pause
exit

:3
echo Analyzing brainwaves...
echo Scanning memories...
echo Calculating probabilities...
echo Decoding thoughts...
echo You are thinking of the number %input%.
pause
exit

:4
echo Analyzing brainwaves...
echo Scanning memories...
echo Calculating probabilities...
echo Decoding thoughts...
echo You are thinking of the number %input%.
pause
exit

:5
echo Analyzing brainwaves...
echo Scanning memories...
echo Calculating probabilities...
echo Decoding thoughts...
echo You are thinking of the number %input%.
pause
exit

:6
echo Analyzing brainwaves...
echo Scanning memories...
echo Calculating probabilities...
echo Decoding thoughts...
echo You are thinking of the number %input%.
pause
exit

:7
echo Analyzing brainwaves...
echo Scanning memories...
echo Calculating probabilities...
echo Decoding thoughts...
echo You are thinking of the number %input%.
pause
exit

:8
echo Analyzing brainwaves...
echo Scanning memories...
echo Calculating probabilities...
echo Decoding thoughts...
echo You are thinking of the number %input%.
pause
exit

:9
echo Analyzing brainwaves...
echo Scanning memories...
echo Calculating probabilities...
echo Decoding thoughts...
echo You are thinking of the number %input%.
pause
exit

:10
echo Analyzing brainwaves...
echo Scanning memories...
echo Calculating probabilities...
echo Decoding thoughts...
echo You are thinking of the number %input%.
pause
exit

:11
echo Analyzing brainwaves...
echo Scanning memories...
echo Calculating probabilities...
echo Decoding thoughts...
echo You are thinking of the number %input%.
pause
exit

:error
echo Sorry, but the number you entered was not between 1-10.
echo.
pause
goto 1